# Generated by Django 3.1.5 on 2021-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_core', '0006_auto_20210421_1417'),
        ('custom_user', '0007_auto_20210420_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked_countdowns',
            field=models.ManyToManyField(related_name='user_bookmarks', to='countdown_core.Countdown'),
        ),
    ]
