# Generated by Django 3.1.5 on 2021-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='finished_text',
            field=models.TextField(blank=True),
        ),
    ]
