# Generated by Django 3.1.5 on 2021-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_core', '0002_countdown_finished_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='finished_text',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
