# Generated by Django 3.1.5 on 2021-04-16 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countdown_core', '0003_auto_20210413_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='cry_reaction',
            field=models.ManyToManyField(related_name='cry_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countdown',
            name='laugh_reaction',
            field=models.ManyToManyField(related_name='lough_reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countdown',
            name='love_reaction',
            field=models.ManyToManyField(related_name='love_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countdown',
            name='negative_reaction',
            field=models.ManyToManyField(related_name='negative_reaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
