# Generated by Django 3.1.5 on 2021-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_core', '0005_auto_20210419_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
