# Generated by Django 3.1.5 on 2021-04-22 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countdown_core', '0006_auto_20210421_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('laugh', models.BooleanField(default=False)),
                ('cry', models.BooleanField(default=False)),
                ('countdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countdown_core.countdown')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
